[build]
  command = "gatsby build" # the command you run to build this file
  functions = "public-lambda" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "public" # Netlify should serve all these files statically

